<?php

use yii\db\Migration;

/**
 * Handles the creation of table `country`.
 */
class m170730_091311_create_country_table extends Migration
{
    /**
     * @inheritdoc
     */
    public function safeUp()
    {
	    $this->createTable('country', [
            'code' => $this->string(2)->notNull(),
	        'lcode' => $this->string(3)->notNull()->defaultValue(''),
	        'currency_id' => $this->string(3)->null(),
	        'name' => $this->string(64)->notNull(),
	        'timezone' => $this->string(40)->null(),
        ], 'CHARACTER SET utf8 DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB');

	    $this->addPrimaryKey('code', 'country', 'code');

	    $this->batchInsert('country', ['code', 'lcode', 'currency_id', 'name', 'timezone'],
	    [
		    ['AU','AUS','AUD','Австралия',null],
		    ['AT','AUT','EUR','Австрия','Europe/Vienna'],
		    ['AZ','AZE','AZN','Азербайджан','Asia/Baku'],
		    ['AX','ALA','EUR','Аландские о-ва',null],
		    ['AL','ALB','ALL','Албания','Europe/Tirane'],
		    ['DZ','DZA','DZD','Алжир','Africa/Algiers'],
		    ['AS','ASM','USD','Американское Самоа',null],
		    ['AI','AIA','XCD','Ангилья','America/Anguilla'],
		    ['AO','AGO','AOA','Ангола','Africa/Luanda'],
		    ['AD','AND','EUR','Андорра','Europe/Andorra'],
		    ['AQ','ATA',null,'Антарктида',null],
		    ['AG','ATG','XCD','Антигуа и Барбуда','America/Antigua'],
		    ['AR','ARG','ARS','Аргентина',null],
		    ['AM','ARM','AMD','Армения','Asia/Yerevan'],
		    ['AW','ABW','AWG','Аруба',null],
		    ['AF','AFG','AFN','Афганистан','Asia/Kabul'],
		    ['BS','BHS','BSD','Багамские о-ва','America/Nassau'],
		    ['BD','BGD','BDT','Бангладеш','Asia/Dhaka'],
		    ['BB','BRB','BBD','Барбадос','America/Barbados'],
		    ['BH','BHR','BHD','Бахрейн','Asia/Bahrain'],
		    ['BY','BLR','BYR','Беларусь','Europe/Minsk'],
		    ['BZ','BLZ','BZD','Белиз','America/Belize'],
		    ['BE','BEL','EUR','Бельгия','Europe/Brussels'],
		    ['BJ','BEN','XOF','Бенин','Africa/Porto-Novo'],
		    ['BM','BMU','BMD','Бермудские о-ва','Atlantic/Bermuda'],
		    ['BG','BGR','BGN','Болгария','Europe/Sofia'],
		    ['BO','BOL','BOB','Боливия','America/La_Paz'],
		    ['BQ','BES','USD','Бонэйр, Синт-Эстатиус и Саба',null],
		    ['BA','BIH','BAM','Босния и Герцеговина','Europe/Sarajevo'],
		    ['BW','BWA','BWP','Ботсвана','Africa/Gaborone'],
		    ['BR','BRA','BRL','Бразилия',null],
		    ['IO','IOT','USD','Британская территория в Индийском океане',null],
		    ['BN','BRN','BND','Бруней-Даруссалам','Asia/Brunei'],
		    ['BF','BFA','XOF','Буркина-Фасо','Africa/Ouagadougou'],
		    ['BI','BDI','BIF','Бурунди','Africa/Bujumbura'],
		    ['BT','BTN','BTN','Бутан','Asia/Thimphu'],
		    ['VU','VUT','VUV','Вануату','Pacific/Efate'],
		    ['VA','VAT','EUR','Ватикан',null],
		    ['GB','GBR','GBP','Великобритания','Europe/London'],
		    ['HU','HUN','HUF','Венгрия','Europe/Budapest'],
		    ['VE','VEN','VEF','Венесуэла','America/Caracas'],
		    ['VG','VGB','USD','Виргинские о-ва (Британские)','America/Tortola'],
		    ['VI','VIR','USD','Виргинские о-ва (США)',null],
		    ['UM','UMI','USD','Внешние малые о-ва (США)',null],
		    ['TL','TLS','USD','Восточный Тимор','Asia/Dili'],
		    ['VN','VNM','VND','Вьетнам','Asia/Ho_Chi_Minh'],
		    ['GA','GAB','XAF','Габон','Africa/Libreville'],
		    ['HT','HTI','HTG','Гаити','America/Port-au-Prince'],
		    ['GY','GUY','GYD','Гайана','America/Guyana'],
		    ['GM','GMB','GMD','Гамбия','Africa/Banjul'],
		    ['GH','GHA','GHS','Гана','Africa/Accra'],
		    ['GP','GLP','EUR','Гваделупа',null],
		    ['GT','GTM','GTQ','Гватемала','America/Guatemala'],
		    ['GN','GIN','GNF','Гвинея','Africa/Conakry'],
		    ['GW','GNB','XOF','Гвинея-Бисау','Africa/Bissau'],
		    ['DE','DEU','EUR','Германия','Europe/Berlin'],
		    ['GG','GGY','GBP','Гернси','Europe/Guernsey'],
		    ['GI','GIB','GIP','Гибралтар','Europe/Gibraltar'],
		    ['HN','HND','HNL','Гондурас','America/Tegucigalpa'],
		    ['HK','HKG','HKD','Гонконг (особый район)',null],
		    ['GD','GRD','XCD','Гренада','America/Grenada'],
		    ['GL','GRL','DKK','Гренландия',null],
		    ['GR','GRC','EUR','Греция','Europe/Athens'],
		    ['GE','GEO','GEL','Грузия','Asia/Tbilisi'],
		    ['GU','GUM','USD','Гуам',null],
		    ['DK','DNK','DKK','Дания','Europe/Copenhagen'],
		    ['JE','JEY','GBP','Джерси','Europe/Jersey'],
		    ['DJ','DJI','DJF','Джибути','Africa/Djibouti'],
		    ['DG','',null,'Диего-Гарсия',null],
		    ['DM','DMA','XCD','Доминика','America/Dominica'],
		    ['DO','DOM','DOP','Доминиканская Республика','America/Santo_Domingo'],
		    ['EG','EGY','EGP','Египет','Africa/Cairo'],
		    ['ZM','ZMB','ZMW','Замбия','Africa/Lusaka'],
		    ['EH','ESH','MAD','Западная Сахара',null],
		    ['ZW','ZWE','ZWL','Зимбабве','Africa/Harare'],
		    ['IL','ISR','ILS','Израиль','Asia/Jerusalem'],
		    ['IN','IND','INR','Индия','Asia/Kolkata'],
		    ['ID','IDN','IDR','Индонезия',null],
		    ['JO','JOR','JOD','Иордания','Asia/Amman'],
		    ['IQ','IRQ','IQD','Ирак','Asia/Baghdad'],
		    ['IR','IRN','IRR','Иран','Asia/Tehran'],
		    ['IE','IRL','EUR','Ирландия','Europe/Dublin'],
		    ['IS','ISL','ISK','Исландия','Atlantic/Reykjavik'],
		    ['ES','ESP','EUR','Испания',null],
		    ['IT','ITA','EUR','Италия','Europe/Rome'],
		    ['YE','YEM','YER','Йемен','Asia/Aden'],
		    ['CV','CPV','CVE','Кабо-Верде','Atlantic/Cape_Verde'],
		    ['KZ','KAZ','KZT','Казахстан',null],
		    ['KY','CYM','KYD','Каймановы о-ва','America/Cayman'],
		    ['KH','KHM','KHR','Камбоджа','Asia/Phnom_Penh'],
		    ['CM','CMR','XAF','Камерун','Africa/Douala'],
		    ['CA','CAN','CAD','Канада',null],
		    ['IC','',null,'Канарские о-ва',null],
		    ['QA','QAT','QAR','Катар','Asia/Qatar'],
		    ['KE','KEN','KES','Кения','Africa/Nairobi'],
		    ['CY','CYP','EUR','Кипр','Asia/Nicosia'],
		    ['KG','KGZ','KGS','Киргизия','Asia/Bishkek'],
		    ['KI','KIR','AUD','Кирибати',null],
		    ['CN','CHN','CNY','Китай',null],
		    ['KP','PRK','KPW','КНДР','Asia/Pyongyang'],
		    ['CC','CCK','AUD','Кокосовые о-ва',null],
		    ['CO','COL','COP','Колумбия','America/Bogota'],
		    ['KM','COM','KMF','Коморские о-ва','Indian/Comoro'],
		    ['CG','COG','XAF','Конго - Браззавиль','Africa/Brazzaville'],
		    ['CD','COD','CDF','Конго - Киншаса',null],
		    ['XK','XKX','EUR','Косово',null],
		    ['CR','CRI','CRC','Коста-Рика','America/Costa_Rica'],
		    ['CI','CIV','XOF','Кот-д’Ивуар','Africa/Abidjan'],
		    ['CU','CUB','CUP','Куба','America/Havana'],
		    ['KW','KWT','KWD','Кувейт','Asia/Kuwait'],
		    ['CW','CUW','ANG','Кюрасао',null],
		    ['LA','LAO','LAK','Лаос','Asia/Vientiane'],
		    ['LV','LVA','EUR','Латвия','Europe/Riga'],
		    ['LS','LSO','LSL','Лесото','Africa/Maseru'],
		    ['LR','LBR','LRD','Либерия','Africa/Monrovia'],
		    ['LB','LBN','LBP','Ливан','Asia/Beirut'],
		    ['LY','LBY','LYD','Ливия','Africa/Tripoli'],
		    ['LT','LTU','EUR','Литва','Europe/Vilnius'],
		    ['LI','LIE','CHF','Лихтенштейн','Europe/Vaduz'],
		    ['LU','LUX','EUR','Люксембург','Europe/Luxembourg'],
		    ['MU','MUS','MUR','Маврикий','Indian/Mauritius'],
		    ['MR','MRT','MRO','Мавритания','Africa/Nouakchott'],
		    ['MG','MDG','MGA','Мадагаскар','Indian/Antananarivo'],
		    ['YT','MYT','EUR','Майотта',null],
		    ['MO','MAC','MOP','Макао (особый район)',null],
		    ['MK','MKD','MKD','Македония','Europe/Skopje'],
		    ['MW','MWI','MWK','Малави','Africa/Blantyre'],
		    ['MY','MYS','MYR','Малайзия',null],
		    ['ML','MLI','XOF','Мали','Africa/Bamako'],
		    ['MV','MDV','MVR','Мальдивские о-ва','Indian/Maldives'],
		    ['MT','MLT','EUR','Мальта','Europe/Malta'],
		    ['MA','MAR','MAD','Марокко','Africa/Rabat'],
		    ['MQ','MTQ','EUR','Мартиника',null],
		    ['MH','MHL','USD','Маршалловы о-ва',null],
		    ['MX','MEX','MXN','Мексика',null],
		    ['MZ','MOZ','MZN','Мозамбик','Africa/Maputo'],
		    ['MD','MDA','MDL','Молдова','Europe/Chisinau'],
		    ['MC','MCO','EUR','Монако','Europe/Monaco'],
		    ['MN','MNG','MNT','Монголия','Asia/Choibalsan'],
		    ['MS','MSR','XCD','Монтсеррат','America/Montserrat'],
		    ['MM','MMR','MMK','Мьянма (Бирма)','Asia/Rangoon'],
		    ['NA','NAM','NAD','Намибия','Africa/Windhoek'],
		    ['NR','NRU','AUD','Науру','Pacific/Nauru'],
		    ['NP','NPL','NPR','Непал','Asia/Kathmandu'],
		    ['NE','NER','XOF','Нигер','Africa/Niamey'],
		    ['NG','NGA','NGN','Нигерия','Africa/Lagos'],
		    ['NL','NLD','EUR','Нидерланды',null],
		    ['NI','NIC','NIO','Никарагуа','America/Managua'],
		    ['NU','NIU','NZD','Ниуэ','Pacific/Niue'],
		    ['NZ','NZL','NZD','Новая Зеландия','Pacific/Auckland'],
		    ['NC','NCL','XPF','Новая Каледония',null],
		    ['NO','NOR','NOK','Норвегия',null],
		    ['AC','',null,'о-в Вознесения',null],
		    ['IM','IMN','GBP','О-в Мэн','Europe/Isle_of_Man'],
		    ['NF','NFK','AUD','о-в Норфолк',null],
		    ['CX','CXR','AUD','о-в Рождества',null],
		    ['SH','SHN','SHP','О-в Св. Елены','Atlantic/St_Helena'],
		    ['CK','COK','NZD','о-ва Кука',null],
		    ['TC','TCA','USD','О-ва Тёркс и Кайкос','America/Grand_Turk'],
		    ['AE','ARE','AED','ОАЭ','Asia/Dubai'],
		    ['OM','OMN','OMR','Оман','Asia/Muscat'],
		    ['PK','PAK','PKR','Пакистан','Asia/Karachi'],
		    ['PW','PLW','USD','Палау','Pacific/Palau'],
		    ['PS','PSE','ILS','Палестинские территории','Asia/Gaza'],
		    ['PA','PAN','PAB','Панама','America/Panama'],
		    ['PG','PNG','PGK','Папуа – Новая Гвинея','Pacific/Port_Moresby'],
		    ['PY','PRY','PYG','Парагвай','America/Asuncion'],
		    ['PE','PER','PEN','Перу','America/Lima'],
		    ['PN','PCN','NZD','Питкэрн','Pacific/Pitcairn'],
		    ['PL','POL','PLN','Польша','Europe/Warsaw'],
		    ['PT','PRT','EUR','Португалия',null],
		    ['PR','PRI','USD','Пуэрто-Рико',null],
		    ['KR','KOR','KRW','Республика Корея','Asia/Seoul'],
		    ['RE','REU','EUR','Реюньон',null],
		    ['RU','RUS','RUB','Россия',null],
		    ['RW','RWA','RWF','Руанда','Africa/Kigali'],
		    ['RO','ROU','RON','Румыния','Europe/Bucharest'],
		    ['SV','SLV','USD','Сальвадор','America/El_Salvador'],
		    ['WS','WSM','WST','Самоа','Pacific/Apia'],
		    ['SM','SMR','EUR','Сан-Марино','Europe/San_Marino'],
		    ['ST','STP','STD','Сан-Томе и Принсипи','Africa/Sao_Tome'],
		    ['SA','SAU','SAR','Саудовская Аравия','Asia/Riyadh'],
		    ['SZ','SWZ','SZL','Свазиленд','Africa/Mbabane'],
		    ['MP','MNP','USD','Северные Марианские о-ва',null],
		    ['SC','SYC','SCR','Сейшельские о-ва','Indian/Mahe'],
		    ['BL','BLM','EUR','Сен-Бартельми',null],
		    ['MF','MAF','EUR','Сен-Мартен',null],
		    ['PM','SPM','EUR','Сен-Пьер и Микелон',null],
		    ['SN','SEN','XOF','Сенегал','Africa/Dakar'],
		    ['VC','VCT','XCD','Сент-Винсент и Гренадины','America/St_Vincent'],
		    ['KN','KNA','XCD','Сент-Китс и Невис','America/St_Kitts'],
		    ['LC','LCA','XCD','Сент-Люсия','America/St_Lucia'],
		    ['RS','SRB','RSD','Сербия','Europe/Belgrade'],
		    ['EA','',null,'Сеута и Мелилья',null],
		    ['SG','SGP','SGD','Сингапур','Asia/Singapore'],
		    ['SX','SXM','ANG','Синт-Мартен',null],
		    ['SY','SYR','SYP','Сирия','Asia/Damascus'],
		    ['SK','SVK','EUR','Словакия','Europe/Bratislava'],
		    ['SI','SVN','EUR','Словения','Europe/Ljubljana'],
		    ['US','USA','USD','Соединенные Штаты','America/Port-au-Prince'],
		    ['SB','SLB','SBD','Соломоновы о-ва','Pacific/Guadalcanal'],
		    ['SO','SOM','SOS','Сомали','Africa/Mogadishu'],
		    ['SD','SDN','SDG','Судан','Africa/Khartoum'],
		    ['SR','SUR','SRD','Суринам','America/Paramaribo'],
		    ['SL','SLE','SLL','Сьерра-Леоне','Africa/Freetown'],
		    ['TJ','TJK','TJS','Таджикистан','Asia/Dushanbe'],
		    ['TH','THA','THB','Таиланд','Asia/Bangkok'],
		    ['TW','TWN','TWD','Тайвань','Asia/Taipei'],
		    ['TZ','TZA','TZS','Танзания','Africa/Dar_es_Salaam'],
		    ['TG','TGO','XOF','Того','Africa/Lome'],
		    ['TK','TKL','NZD','Токелау',null],
		    ['TO','TON','TOP','Тонга',null],
		    ['TT','TTO','TTD','Тринидад и Тобаго','America/Port_of_Spain'],
		    ['TA','',null,'Тристан-да-Кунья',null],
		    ['TV','TUV','AUD','Тувалу','Pacific/Funafuti'],
		    ['TN','TUN','TND','Тунис','Africa/Tunis'],
		    ['TM','TKM','TMT','Туркменистан','Asia/Ashgabat'],
		    ['TR','TUR','TRY','Турция','Europe/Istanbul'],
		    ['UG','UGA','UGX','Уганда','Africa/Kampala'],
		    ['UZ','UZB','UZS','Узбекистан','Asia/Tashkent'],
		    ['UA','UKR','UAH','Украина',null],
		    ['WF','WLF','XPF','Уоллис и Футуна',null],
		    ['UY','URY','UYU','Уругвай','America/Montevideo'],
		    ['FO','FRO','DKK','Фарерские о-ва','Atlantic/Faroe'],
		    ['FM','FSM','USD','Федеративные Штаты Микронезии',null],
		    ['FJ','FJI','FJD','Фиджи','Pacific/Fiji'],
		    ['PH','PHL','PHP','Филиппины','Asia/Manila'],
		    ['FI','FIN','EUR','Финляндия','Europe/Helsinki'],
		    ['FK','FLK','FKP','Фолклендские о-ва','Atlantic/Stanley'],
		    ['FR','FRA','EUR','Франция',null],
		    ['GF','GUF','EUR','Французская Гвиана',null],
		    ['PF','PYF','XPF','Французская Полинезия',null],
		    ['TF','ATF','EUR','Французские Южные Территории',null],
		    ['HR','HRV','HRK','Хорватия','Europe/Zagreb'],
		    ['CF','CAF','XAF','ЦАР','Africa/Bangui'],
		    ['TD','TCD','XAF','Чад','Africa/Ndjamena'],
		    ['ME','MNE','EUR','Черногория','Europe/Podgorica'],
		    ['CZ','CZE','CZK','Чехия',null],
		    ['CL','CHL','CLP','Чили','America/Santiago'],
		    ['CH','CHE','CHF','Швейцария','Europe/Zurich'],
		    ['SE','SWE','SEK','Швеция','Europe/Stockholm'],
		    ['SJ','SJM','NOK','Шпицберген и Ян-Майен',null],
		    ['LK','LKA','LKR','Шри-Ланка','Asia/Colombo'],
		    ['EC','ECU','USD','Эквадор','America/Guayaquil'],
		    ['GQ','GNQ','XAF','Экваториальная Гвинея','Africa/Malabo'],
		    ['ER','ERI','ERN','Эритрея','Africa/Asmara'],
		    ['EE','EST','EUR','Эстония','Europe/Tallinn'],
		    ['ET','ETH','ETB','Эфиопия','Africa/Addis_Ababa'],
		    ['ZA','ZAF','ZAR','ЮАР','Africa/Johannesburg'],
		    ['GS','SGS','GBP','Южная Георгия и Южные Сандвичевы о-ва','Atlantic/South_Georgia'],
		    ['SS','SSD','SSP','Южный Судан','Africa/Juba'],
		    ['JM','JAM','JMD','Ямайка','America/Jamaica'],
		    ['JP','JPN','JPY','Япония','Asia/Tokyo']
	    ]);

	    $this->createIndex(
		    'idx-country-currency_id',
		    'country',
		    'currency_id'
	    );

	    $this->addForeignKey(
		    'fk-country-currency_id',
		    'country',
		    'currency_id',
		    'currency',
		    'code',
		    'SET NULL'
	    );
    }

    /**
     * @inheritdoc
     */
    public function safeDown()
    {
	    $this->dropForeignKey(
		    'fk-country-currency_id',
		    'country'
	    );

	    $this->dropIndex(
		    'idx-country-currency_id',
		    'country'
	    );

        $this->dropTable('country');
    }
}
